# Generated by Django 2.1.2 on 2018-11-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='CATEGORY'),
        ),
    ]
