# Generated by Django 2.1.2 on 2018-10-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
